package main

import (
	"testing"
	"net/http"
	"fmt"
	"encoding/json"
)

func TestMovie(t *testing.T)  {
	resp,err := http.Get("http://m.maoyan.com/ajax/movieOnInfoList")
	if err != nil {
		fmt.Println(err)
	}
	obj := AutoGeneratedMovie{}
	json.NewDecoder(resp.Body).Decode(&obj)

	fmt.Println(obj)

}