package main

import (
	"testing"
	"net/http"
	"encoding/json"
	"html/template"
	"os"
	"io"
)

func TestMovie(ttt *testing.T)  {
	resp,err := http.Get("http://m.maoyan.com/ajax/movieOnInfoList")
	if err != nil {
		ttt.Error(err)
	}
	defer resp.Body.Close()
	obj := AutoGeneratedMovie{}
	json.NewDecoder(resp.Body).Decode(&obj)



	t, err := template.ParseFiles("template/movies")  //解析模板文件
	if err != nil {
		ttt.Error(err)
	}

	file, err := os.Create("output/movies.md")
	if err != nil {
		ttt.Error(err)
	}

	err = t.Execute(file, obj)  //执行模板的merger操作
	if err != nil {
		ttt.Error(err)
	}
	io.Copy(os.Stdout, file)

	file.Close()

}


